ALTER TABLE users ADD COLUMN IF NOT EXISTS isSuspended BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS suspensionReason VARCHAR(191) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS suspendedAt DATETIME(3) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS softBannedAt DATETIME(3) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS isAdmin BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS adminRole ENUM('SUPER_ADMIN','OPS_ADMIN','SUPPORT_ADMIN') NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS verificationToken VARCHAR(191) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS resetToken VARCHAR(191) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS resetTokenExpiry DATETIME(3) NULL;
